# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Arq < Formula
  desc "Local arXiv paper index for fzf-driven exploration"
  homepage "https://github.com/orangekame3/arq"
  version "0.0.14"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/orangekame3/arq/releases/download/v0.0.14/arq_Darwin_x86_64.tar.gz"
      sha256 "265e572db1885fcddf7a358ea80a57317a25c967dc6092d273e593805d1ae3b8"

      define_method(:install) do
        bin.install "arq"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/orangekame3/arq/releases/download/v0.0.14/arq_Darwin_arm64.tar.gz"
      sha256 "8013ecb0e6bf1236fa75b3dff28c62b09ff2ab2950490700151185b529b63be9"

      define_method(:install) do
        bin.install "arq"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/orangekame3/arq/releases/download/v0.0.14/arq_Linux_x86_64.tar.gz"
      sha256 "94fde983711dfa3688d015b9011d80ba63b8eff6b0dcce61020de677250e0986"
      define_method(:install) do
        bin.install "arq"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/orangekame3/arq/releases/download/v0.0.14/arq_Linux_arm64.tar.gz"
      sha256 "a756557af20ffd3c966be799e5b6ef26debed475c1d1433e289dd22dddd819e5"
      define_method(:install) do
        bin.install "arq"
      end
    end
  end

  test do
    system "#{bin}/arq", "--help"
  end
end
