# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CobraTemplate < Formula
  desc ""
  homepage ""
  version "0.0.8"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/orangekame3/cobra-template/releases/download/v0.0.8/cobra-template_Darwin_x86_64.tar.gz"
      sha256 "77a45c82406c1a660b9fbe39cfd620e290af9f8d973791e058464a60047972ed"

      def install
        bin.install "cobra-template"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/orangekame3/cobra-template/releases/download/v0.0.8/cobra-template_Darwin_arm64.tar.gz"
      sha256 "f32586190332e11a6e17f2380cbf20d1ab0130d48f2cc61c62b9def13ac50363"

      def install
        bin.install "cobra-template"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/orangekame3/cobra-template/releases/download/v0.0.8/cobra-template_Linux_arm64.tar.gz"
      sha256 "205ca8b1c6d41e1f838828c46198a73412171cf47719725aef885e5692606e1e"

      def install
        bin.install "cobra-template"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/orangekame3/cobra-template/releases/download/v0.0.8/cobra-template_Linux_x86_64.tar.gz"
      sha256 "7ddf4aec14bb2e8906cb1b632f11c77c1c116ec19fb06fb416a7453cea48dcc3"

      def install
        bin.install "cobra-template"
      end
    end
  end
end
