# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ghfetch < Formula
  desc ""
  homepage ""
  version "0.0.17"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/orangekame3/ghfetch/releases/download/v0.0.17/ghfetch_Darwin_arm64.tar.gz"
      sha256 "ac799c090cd187b346e1b37a052982ed8cdeb46b0ab6ca20d62276a412cc27e2"

      def install
        bin.install "ghfetch"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/orangekame3/ghfetch/releases/download/v0.0.17/ghfetch_Darwin_x86_64.tar.gz"
      sha256 "7551f429f2e9f433200e2a77319aab5df7e93b0a0e5e78e5286dc64f8a39b8e0"

      def install
        bin.install "ghfetch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/orangekame3/ghfetch/releases/download/v0.0.17/ghfetch_Linux_arm64.tar.gz"
      sha256 "b5f749e241bc05bacce93b99e89cabbd80787dc3016e36ee33f57df5e490267b"

      def install
        bin.install "ghfetch"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/orangekame3/ghfetch/releases/download/v0.0.17/ghfetch_Linux_x86_64.tar.gz"
      sha256 "a0db083464361d80fa58f77849dc4778d66ffaa8f15d8968d677a2cde7aa81c3"

      def install
        bin.install "ghfetch"
      end
    end
  end
end
