# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ghfetch < Formula
  desc ""
  homepage ""
  version "0.0.11"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/orangekame3/ghfetch/releases/download/v0.0.11/ghfetch_Darwin_x86_64.tar.gz"
      sha256 "847809e7a40da380a5a9789110ec7d7568a13a9bfbd01fa79560a597721d6b60"

      def install
        bin.install "ghfetch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/orangekame3/ghfetch/releases/download/v0.0.11/ghfetch_Darwin_arm64.tar.gz"
      sha256 "ff330f5a83991d4efa12c179bbbc72233cdf054c50946392f0cbc5168a825a9f"

      def install
        bin.install "ghfetch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/orangekame3/ghfetch/releases/download/v0.0.11/ghfetch_Linux_arm64.tar.gz"
      sha256 "b4bcf6680ae7fc76c413189656598e462d1aad379bedd86c5247d899de694a3e"

      def install
        bin.install "ghfetch"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/orangekame3/ghfetch/releases/download/v0.0.11/ghfetch_Linux_x86_64.tar.gz"
      sha256 "b430821734046019436e708bb69602fb2cabc24a36efb22ca58ffca178840fc2"

      def install
        bin.install "ghfetch"
      end
    end
  end
end
