# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ghfetch < Formula
  desc ""
  homepage ""
  version "0.0.12"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/orangekame3/ghfetch/releases/download/v0.0.12/ghfetch_Darwin_x86_64.tar.gz"
      sha256 "3188adcae59d6c7f9f3a0f73cb7ca5f1093521066a4573b197c4dc994203f6fa"

      def install
        bin.install "ghfetch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/orangekame3/ghfetch/releases/download/v0.0.12/ghfetch_Darwin_arm64.tar.gz"
      sha256 "cffb344aa903fb028d5b522d8c270b1f6cd14f844b7d49a5e0d6bdbbe278ed72"

      def install
        bin.install "ghfetch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/orangekame3/ghfetch/releases/download/v0.0.12/ghfetch_Linux_arm64.tar.gz"
      sha256 "11e228dae5edcca8af9e0df773c49e0523485c72031e76686fd90e06b85d59a8"

      def install
        bin.install "ghfetch"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/orangekame3/ghfetch/releases/download/v0.0.12/ghfetch_Linux_x86_64.tar.gz"
      sha256 "9772fd235df18c389422e8c88f53e93cd6d92cf0cbed39bf48e026794d01d088"

      def install
        bin.install "ghfetch"
      end
    end
  end
end
