# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mk < Formula
  desc ""
  homepage ""
  version "0.0.15"

  on_macos do
    on_intel do
      url "https://github.com/orangekame3/mk/releases/download/v0.0.15/mk_0.0.15_darwin_amd64.tar.gz"
      sha256 "ff559207b453b356ef33d72dd45230ed2b6cc0653ce0e3ae2e820d4bed2080ff"

      def install
        bin.install "mk"
      end
    end
    on_arm do
      url "https://github.com/orangekame3/mk/releases/download/v0.0.15/mk_0.0.15_darwin_arm64.tar.gz"
      sha256 "fd2e6bf20b99abd0825c597d437d3daf5ec78bba7015ffd35e513acb007271a7"

      def install
        bin.install "mk"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/orangekame3/mk/releases/download/v0.0.15/mk_0.0.15_linux_amd64.tar.gz"
        sha256 "cac61ccd9e28bb34f66e9167011dfa628402a051969a735e25030f570d5e36c2"

        def install
          bin.install "mk"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/orangekame3/mk/releases/download/v0.0.15/mk_0.0.15_linux_arm64.tar.gz"
        sha256 "798e49558ca3f5363a9d624b4a60efa500b7fbaf151977241f9dbf041ad3fb63"

        def install
          bin.install "mk"
        end
      end
    end
  end
end
