# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Oqx < Formula
  desc "CLI for the OQTOPUS Cloud User API"
  homepage "https://github.com/orangekame3/oqx"
  version "0.0.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/orangekame3/oqx/releases/download/v0.0.1/oqx_Darwin_x86_64.tar.gz"
      sha256 "724f5b1fba107a5618a1fa8791592179cfd7162ee1bcac169025810d9b4f00e1"

      define_method(:install) do
        bin.install "oqx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/orangekame3/oqx/releases/download/v0.0.1/oqx_Darwin_arm64.tar.gz"
      sha256 "c3e2de38d41cb0baf865ed9431e2fc2e1dd01c2cf0694111c3d59e56ae5bfedd"

      define_method(:install) do
        bin.install "oqx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/orangekame3/oqx/releases/download/v0.0.1/oqx_Linux_x86_64.tar.gz"
      sha256 "0861f8be68f97a5c585d53a26a29db8e1654d03a7666c8237f8c6a08facf0158"
      define_method(:install) do
        bin.install "oqx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/orangekame3/oqx/releases/download/v0.0.1/oqx_Linux_arm64.tar.gz"
      sha256 "bcee025209d15d5c128ef9d62b680ee1ccd86dd5097a1924bca3171fc21b889d"
      define_method(:install) do
        bin.install "oqx"
      end
    end
  end

  test do
    system "#{bin}/oqx", "--help"
  end
end
