# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Paclear < Formula
  desc ""
  homepage ""
  version "0.0.11"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/orangekame3/paclear/releases/download/v0.0.11/paclear_Darwin_x86_64.tar.gz"
      sha256 "c7c3a6eb8d95d0def2bb8c27bd92911336ed260761e3b9731cfea49e9668792b"

      def install
        bin.install "paclear"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/orangekame3/paclear/releases/download/v0.0.11/paclear_Darwin_arm64.tar.gz"
      sha256 "fd3c5e6580b09b63b5dc2ac0eea12122f641b15a8e3a06af28429713070b8399"

      def install
        bin.install "paclear"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/orangekame3/paclear/releases/download/v0.0.11/paclear_Linux_x86_64.tar.gz"
      sha256 "d9b7eb8354717219e8350599ed95176c0535d9f4664d1dd17a6671c3af27bcec"

      def install
        bin.install "paclear"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/orangekame3/paclear/releases/download/v0.0.11/paclear_Linux_arm64.tar.gz"
      sha256 "39133f88b59aba03eb8206fe19f30f90e7c34f3b1d33e0bee7f300b959f84b0f"

      def install
        bin.install "paclear"
      end
    end
  end
end
