# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Paclear < Formula
  desc ""
  homepage ""
  version "0.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/orangekame3/paclear/releases/download/v0.0.2/paclear_Darwin_x86_64.tar.gz"
      sha256 "e5676fb1eefa312b6210ccc3f32c3bc8e87f8430504b11984ad4ea2752ba1b78"

      def install
        bin.install "paclear"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/orangekame3/paclear/releases/download/v0.0.2/paclear_Darwin_arm64.tar.gz"
      sha256 "7d8e7b1874ebe476014f2b596692277d4dc212332044f2da33633a95b6405f75"

      def install
        bin.install "paclear"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/orangekame3/paclear/releases/download/v0.0.2/paclear_Linux_arm64.tar.gz"
      sha256 "2df564057e2a59809c6cac7f501b6074336b891bc4cf1d2f7257fbe0e793d1b6"

      def install
        bin.install "paclear"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/orangekame3/paclear/releases/download/v0.0.2/paclear_Linux_x86_64.tar.gz"
      sha256 "3bb00b36ab0a1d1818014ddea2c2c7a3b6e3cc81c8edd6a9532d637cd0232c2c"

      def install
        bin.install "paclear"
      end
    end
  end
end
