# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Paclear < Formula
  desc ""
  homepage ""
  version "0.0.5"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/orangekame3/paclear/releases/download/v0.0.5/paclear_Darwin_arm64.tar.gz"
      sha256 "e8f317565eee6ad61bdf7d13277f6da96c9e877fce6ea40f072368b0f86f7966"

      def install
        bin.install "paclear"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/orangekame3/paclear/releases/download/v0.0.5/paclear_Darwin_x86_64.tar.gz"
      sha256 "7d48fc6c47071f9c29464d60eb9b3b768201343f185617af71b33545a1721617"

      def install
        bin.install "paclear"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/orangekame3/paclear/releases/download/v0.0.5/paclear_Linux_x86_64.tar.gz"
      sha256 "ae5af7066498de0e50eee9a07fbba2c78cc054ec526d861f0236383086aa266d"

      def install
        bin.install "paclear"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/orangekame3/paclear/releases/download/v0.0.5/paclear_Linux_arm64.tar.gz"
      sha256 "aea700d210f7aea818ae24d2a4aad45fccbe8bca588bcdbd6d24bbddc187a98e"

      def install
        bin.install "paclear"
      end
    end
  end
end
