# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Qasmtools < Formula
  desc "QASM tools for formatting, linting, and parsing OpenQASM 3.0 files"
  homepage "https://github.com/orangekame3/qasmtools"
  version "0.2.10"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/orangekame3/qasmtools/releases/download/v0.2.10/qasmtools_Darwin_x86_64.tar.gz"
      sha256 "ced04d17248944319524566f2eaa3befb1a53078dc66a2706348e34969b6b52f"

      def install
        bin.install "qasm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/orangekame3/qasmtools/releases/download/v0.2.10/qasmtools_Darwin_arm64.tar.gz"
      sha256 "4e79069a01a5153bc2056dbc53a4637007933cc844d223b0b665690f99fdcb71"

      def install
        bin.install "qasm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/orangekame3/qasmtools/releases/download/v0.2.10/qasmtools_Linux_x86_64.tar.gz"
      sha256 "a9530215a7dde6f2b1b0e30e84e24b1933788980a57263b42d1ba1ac88a325cd"
      def install
        bin.install "qasm"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/orangekame3/qasmtools/releases/download/v0.2.10/qasmtools_Linux_arm64.tar.gz"
      sha256 "8b6b28a0d2ba8120875f7df992aa5af0c9bfc67bb390172ffc91e7b88d7f57d4"
      def install
        bin.install "qasm"
      end
    end
  end

  test do
    system "#{bin}/qasm", "--version"
  end
end
