# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Qasmtools < Formula
  desc "QASM tools for formatting, linting, and parsing OpenQASM 3.0 files"
  homepage "https://github.com/orangekame3/qasmtools"
  version "0.2.12"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/orangekame3/qasmtools/releases/download/v0.2.12/qasmtools_Darwin_x86_64.tar.gz"
      sha256 "b87ee10ad49adf11b26b1cd6b3d0b86e00cd40b4353981940a2e7e886a1a4b86"

      def install
        bin.install "qasm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/orangekame3/qasmtools/releases/download/v0.2.12/qasmtools_Darwin_arm64.tar.gz"
      sha256 "f89eb85c3d4ff3f8822e4c470eb47316bca3d38d90479f2eb1a128cb618e83cf"

      def install
        bin.install "qasm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/orangekame3/qasmtools/releases/download/v0.2.12/qasmtools_Linux_x86_64.tar.gz"
      sha256 "31dfffe7b5cb7365e3eca68178ae83e8a57eb91000475cc776a1227c1ea7b844"
      def install
        bin.install "qasm"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/orangekame3/qasmtools/releases/download/v0.2.12/qasmtools_Linux_arm64.tar.gz"
      sha256 "214f69b2e7a064eb3ba97cd437172bb65557b654dc916f443cef24d27459dcae"
      def install
        bin.install "qasm"
      end
    end
  end

  test do
    system "#{bin}/qasm", "--version"
  end
end
