# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stree < Formula
  desc ""
  homepage ""
  version "0.0.15"

  on_macos do
    on_intel do
      url "https://github.com/orangekame3/stree/releases/download/v0.0.15/stree_0.0.15_darwin_amd64.tar.gz"
      sha256 "ea6b14ec4f372e77bfa579271fa0b9edfb585779f02fdeff94ffcb2a35db5db6"

      def install
        bin.install "stree"
      end
    end
    on_arm do
      url "https://github.com/orangekame3/stree/releases/download/v0.0.15/stree_0.0.15_darwin_arm64.tar.gz"
      sha256 "090957ded686c8122e9de2591afe63fcb3f4eb3af9f86c68c87bbfdaa120e3d9"

      def install
        bin.install "stree"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/orangekame3/stree/releases/download/v0.0.15/stree_0.0.15_linux_amd64.tar.gz"
        sha256 "60e1d19e7879a5e99662ea8173d7aa2cfe6f55feda4910b6d57740db89b653db"

        def install
          bin.install "stree"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/orangekame3/stree/releases/download/v0.0.15/stree_0.0.15_linux_arm64.tar.gz"
        sha256 "d1ee0fbc1b5a72098bae62999ec473bd3b381b66abae3a7e7dca2e202aa453b4"

        def install
          bin.install "stree"
        end
      end
    end
  end
end
