# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stree < Formula
  desc ""
  homepage ""
  version "0.0.19"

  on_macos do
    on_intel do
      url "https://github.com/orangekame3/stree/releases/download/v0.0.19/stree_0.0.19_darwin_amd64.tar.gz"
      sha256 "e7623972262fc9c18d9a0c27e60838b6409f5c8c0204bd523d34c78c34512b1d"

      def install
        bin.install "stree"
      end
    end
    on_arm do
      url "https://github.com/orangekame3/stree/releases/download/v0.0.19/stree_0.0.19_darwin_arm64.tar.gz"
      sha256 "3de2e53bf3839d3dcce6f24755b6e6d66b51e8928c44714ae75520287f586c8b"

      def install
        bin.install "stree"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/orangekame3/stree/releases/download/v0.0.19/stree_0.0.19_linux_amd64.tar.gz"
        sha256 "7688070ff78813c69269ea496d9fc12f8015031970b3d1b381cf787133d9ef8a"

        def install
          bin.install "stree"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/orangekame3/stree/releases/download/v0.0.19/stree_0.0.19_linux_arm64.tar.gz"
        sha256 "0bcb4d87a96c5696ec54e04124069f652ba06850f2ce9f0f20405e4334dd64b6"

        def install
          bin.install "stree"
        end
      end
    end
  end
end
