# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stree < Formula
  desc ""
  homepage ""
  version "0.0.16"

  on_macos do
    on_intel do
      url "https://github.com/orangekame3/stree/releases/download/v0.0.16/stree_0.0.16_darwin_amd64.tar.gz"
      sha256 "fc1fdd1642f4a921ebd6da4d328f2625c3761be92beeeedc8821b98347b4cf7f"

      def install
        bin.install "stree"
      end
    end
    on_arm do
      url "https://github.com/orangekame3/stree/releases/download/v0.0.16/stree_0.0.16_darwin_arm64.tar.gz"
      sha256 "bf7c60337132095dea5de8151166d40ecd208d7396f8cb05ee1621afbd8b85eb"

      def install
        bin.install "stree"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/orangekame3/stree/releases/download/v0.0.16/stree_0.0.16_linux_amd64.tar.gz"
        sha256 "3f51485c9456156360785e1f4f5f4199d8972add69ae3b68e3cd3bc77b385468"

        def install
          bin.install "stree"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/orangekame3/stree/releases/download/v0.0.16/stree_0.0.16_linux_arm64.tar.gz"
        sha256 "f867cf7f36368c1dd08971f4befe2144467f813615d42b8d9d8d335c77e9d944"

        def install
          bin.install "stree"
        end
      end
    end
  end
end
