# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tftarget < Formula
  desc ""
  homepage ""
  version "0.0.36"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/orangekame3/tftarget/releases/download/v0.0.36/tftarget_Darwin_x86_64.tar.gz"
      sha256 "86328ebe2a5d7cf7fcc01edcf078fd079cf4b424d55e41ade46a923e53af9ba1"

      def install
        bin.install "tftarget"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/orangekame3/tftarget/releases/download/v0.0.36/tftarget_Darwin_arm64.tar.gz"
      sha256 "1a82c3f5489b9d2b0abc30bc2356fabc6557567b3cf86319972e2a8635c3d6b7"

      def install
        bin.install "tftarget"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/orangekame3/tftarget/releases/download/v0.0.36/tftarget_Linux_x86_64.tar.gz"
      sha256 "f6d9552ac093755eccccb4d655a849fc5e529e1b71ed33d8b8fc0b6e6cd1e3a0"

      def install
        bin.install "tftarget"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/orangekame3/tftarget/releases/download/v0.0.36/tftarget_Linux_arm64.tar.gz"
      sha256 "d47688c9d606f4bdbb27cde15eb7e6899ae816e25c9d67521829ac4d0bce37e0"

      def install
        bin.install "tftarget"
      end
    end
  end
end
