# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tftarget < Formula
  desc ""
  homepage ""
  version "0.0.37"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/orangekame3/tftarget/releases/download/v0.0.37/tftarget_Darwin_arm64.tar.gz"
      sha256 "126652165f0ac50f372ba7b12c0065c4970802aa5605c8ad22de16daa81d6266"

      def install
        bin.install "tftarget"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/orangekame3/tftarget/releases/download/v0.0.37/tftarget_Darwin_x86_64.tar.gz"
      sha256 "f13a3e35e4914be016c9be3f10c3271590f45335d2d095055a689bcc1a16ce1d"

      def install
        bin.install "tftarget"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/orangekame3/tftarget/releases/download/v0.0.37/tftarget_Linux_x86_64.tar.gz"
      sha256 "7ecae0577c424789d0e425d544aa1930e71d73f5134f9534fa19d6f841d954e7"

      def install
        bin.install "tftarget"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/orangekame3/tftarget/releases/download/v0.0.37/tftarget_Linux_arm64.tar.gz"
      sha256 "ab0f987d6a06c9ab5da9bba3ee177266a584ac6fba3da2f2afb1d1c49e762dc7"

      def install
        bin.install "tftarget"
      end
    end
  end
end
