# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Viff < Formula
  desc ""
  homepage ""
  version "0.0.12"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/orangekame3/viff/releases/download/v0.0.12/viff_Darwin_x86_64.tar.gz"
      sha256 "54d36c937e282a6e2712ec81c434f7beb885ba9c873f42ebb4c56373a708ad9a"

      def install
        bin.install "viff"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/orangekame3/viff/releases/download/v0.0.12/viff_Darwin_arm64.tar.gz"
      sha256 "7bb132c6c25f75be794b61ada85f05fde9e4c95d1b8e5a934883c20d8fd642dd"

      def install
        bin.install "viff"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/orangekame3/viff/releases/download/v0.0.12/viff_Linux_arm64.tar.gz"
      sha256 "16a3b1d79b923361f585e72cf7a2159a073646ce211fc6144e534b0afc28df96"

      def install
        bin.install "viff"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/orangekame3/viff/releases/download/v0.0.12/viff_Linux_x86_64.tar.gz"
      sha256 "60a9682a50cfc76a717f67805e598ebcb4df02f3d2058c520f010fe06cc0b571"

      def install
        bin.install "viff"
      end
    end
  end
end
