# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Viff < Formula
  desc ""
  homepage ""
  version "0.0.11"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/orangekame3/viff/releases/download/v0.0.11/viff_Darwin_x86_64.tar.gz"
      sha256 "1aea1a9e714f91620905d1ac9f4154a6a22d7501637aacc113733edf9fcc948b"

      def install
        bin.install "viff"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/orangekame3/viff/releases/download/v0.0.11/viff_Darwin_arm64.tar.gz"
      sha256 "ee1669a00cde8fd0e7814c79cd0302da4344022f904eac7c88658f3c2f68b75b"

      def install
        bin.install "viff"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/orangekame3/viff/releases/download/v0.0.11/viff_Linux_arm64.tar.gz"
      sha256 "af8415c3c79851f2bb5e721275a28c169769ae3fa4b9f9d3ae5585fff767fae6"

      def install
        bin.install "viff"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/orangekame3/viff/releases/download/v0.0.11/viff_Linux_x86_64.tar.gz"
      sha256 "c8eb67bb648c706828dea2c96d5be72763940320fdee456d03763c7df3118c6a"

      def install
        bin.install "viff"
      end
    end
  end
end
