# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Viff < Formula
  desc ""
  homepage ""
  version "0.0.9"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/orangekame3/viff/releases/download/v0.0.9/viff_Darwin_arm64.tar.gz"
      sha256 "75cdc50feabaefe3448eef01b1585221594db0310f85c97c33656a3db049b6f0"

      def install
        bin.install "viff"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/orangekame3/viff/releases/download/v0.0.9/viff_Darwin_x86_64.tar.gz"
      sha256 "7513d5edf44de10d3c87f67f9121dd400480ea5323a46f892d71a4822e2eb18e"

      def install
        bin.install "viff"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/orangekame3/viff/releases/download/v0.0.9/viff_Linux_arm64.tar.gz"
      sha256 "b666f174722dee1f51f6b9684ccfbcd3496c74efe0c542f53bf561c349ebe238"

      def install
        bin.install "viff"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/orangekame3/viff/releases/download/v0.0.9/viff_Linux_x86_64.tar.gz"
      sha256 "7ca57c1ddfe58072fb7b9316bfd7fc6fba7c50b2baebdefe0cc461a2ba6b057c"

      def install
        bin.install "viff"
      end
    end
  end
end
