name: Update README

on:
  push:
    paths:
      - '*.rb'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Run Python script to update README
        run: python .github/scripts/update_readme.py
        env:
          GITHUB_ACCOUNT: ${{ github.repository_owner }}
